# Generated by Django 4.2.5 on 2023-11-18 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_bookmark_like_reply_remove_feed_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='email',
        ),
        migrations.AddField(
            model_name='feed',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='profile_image',
            field=models.TextField(default=datetime.datetime(2023, 11, 18, 9, 9, 17, 803728, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feed',
            name='user_id',
            field=models.TextField(default=datetime.datetime(2023, 11, 18, 9, 9, 56, 903950, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
